DESIRED_FEATURE_NAMES = desired_feature_list = [
    "bedrooms",
    "bathrooms",
    "price",
    "price_per_sqft",
    "stories",
    "home_age",
    "home_style",
    "square footage",
    "location",
    "hoa",
    "view",
    "schools",
    "HVAC",
    "home_technology",
    "parking",
    "outdoor_living_space",
    "bonus_room",
    "laundry_facilities",
    "storage",
    "fireplace",
    "kitchen",
    "ceiling",
    "flooring",
    "roof",
    "closet",
    "shower",
    "amenity",
    "natural_light",
    'home_office',
    'open_floor_plan',
    'is_convenient',
    'is_modern',
    'is_luxury',
    'is_comfortable'
]
POST_PROCESSING_BANNED_LOW_FREQUENCY_FEATURES = {
    "price_per_sqft",
    "square footage",
    "price",
    "is_modern"
}
desired_to_originals = {
    'kitchen': {'kitchen_island', 'kitchen_technology', 'kitchenTechnology'},
    'view': {'views'},
    'is_luxury': {'luury', '$is_luxury'},
    'stories': {'story', ' stories', 'Stories', ' Stories'},
    'natural_light': {'Natural_light', 'natual_light'},
    'hoa': {' hoa', 'hoA', 'HOA',},
    'open_floor_plan': {'floor_plan', 'oe_floor_plan', 'open_house', 'floorplan', 'floor_planning',
                        'open-floor_plan', 'floors_plan', 'open_floor-plan'},
    'is_modern': {'id', 'is moden', '$is_modern', 'is现代'},
    'laundry_facilities': {'-laundry_facilities', 'laundry'},
    'flooring': {'.flooring', ' floors', 'floors', 'flooring_description', 'flooding', ' flooring'},
    'home_office': {'office', 'flex_room'},
    'ceiling': {'ceilings', 'fencing', 'vaulted ceiling', 'ceiling_description', 'shelving',
                'independent ceiling'},
    'parking': {'parking_capacity', 'Parkings'},
    'closet': {'sheets', 'bathroom_closet', "mudroom", "cloakroom"},
    'shower': {'bathroom_shower', 'shiwer'},
    'schools': {'schoold', 'school_district', 'schoools', 'sschools', 'sCHOOLS', 'school', 'pool', " schools"},
    'is_comfortable': {'is_confortable', '$is_comfortable',
                       'iscomfortable'},
    'amenity': {'ammenity', 'amentity', 'ämfinity', },
    'storage': {'-storage', '(storage)'},
    'roof': {'rooftop', 'rooft', 'rooof', 'roft', 'rooF', 'roofs'},
    'home_style': {'home_STYLE', ' 홈_style'},
    'square footage': {'square_footage', 'square footage'},
    'home_age': {'HOME AGE'},
    'home_technology': {'HOME技術', '-home_technology', 'Home Technology'},
    'bedrooms': {'master_bedroom', },
    'price': {'price_month'},
    'bathrooms': {'bathrooms_description', 'bathroom', 'bathroom_description', 'bathroom_features', 'cloakroom'},
    'outdoor_living_space': {'.outdoor_living_space', '_outdoor_living_space', 'independent outdoor_living_space'},
    'is_convenient': {'isle_convenient', ' 〉is_convenient', '$is_convenient', '-is_convenient', 'independent view'},
}
