from openai import OpenAI
import pickle
import os

if __name__ == '__main__':

    api_key = "[your-key]"
    os.environ['OPENAI_API_KEY'] = api_key
    # chat_manager = OpenAIChatManager(api_key)
    chat_manager = OpenAI(api_key=api_key, organization='[your-org]', )
    model = "gpt-4-turbo"
    template = f"""Imagine you are a seller agent and you want to sell a house to the customer. 
    We have some preferences from the customer, given in the format of (listings, preferences).
    Please analyze the data carefully and summarize the preferences of the customer with respect to these five demensions: Price, Location, Home features/Amenity, House Size, Investment Value.
    
    [First Batch: Sample Data from the customer]
    
    Here is a short list of houses provided to the customer:
    House 0: 345000, 2 bedrooms, 2 bathrooms, Irving Park, CONDO, 3300 W Irving Park Rd UNIT G2, Stunning 2 bedroom 2 bathroom unit in boutique elevator building. Southern exposure & fantastic natural light compliment the spacious open concept floorplan. Beautiful kitchen with over-sized island & stainless appliances overlooks the large living & dining areas. Primary suite features dual vanity natural stone bathroom & ample closet space. 2nd bedroom easily fits queen or king bed, with 2nd full bathroom right across the hallway. In-unit washer/dryer. Large balcony extended from dining area. Heated garage parking included. Walk to restaurants & coffee shops. Easy access to 90/94, Blue & Brown lines, plus several bus lines.
    House 1: 285000, 4 bedrooms, 2 bathrooms, Grand Crossing, SINGLE_FAMILY, 7445 S Ellis Ave, Welcome to this stunning brick two-story home located in quaint east Chatham; boasting a large lot and in close proximity to the highly-anticipated Obama Library. Step inside spacious and inviting living areas adorned with high ceilings, refinished hardwood floors, and bow windows that fill the home with natural light. Updated kitchen boasts beautiful espresso cabinets, granite countertops, and opens to a patio with access to a large backyard perfect for outdoor gatherings and relaxation. A powder room tucked away by the staircase finishes off this floor. Upstairs, you'll find four bedrooms and an updated bathroom, offering both comfort and style. The basement features a spacious family room, laundry hook up, walk-in storage area, and separate access to the backyard. The yard leads to a 2-car+ garage with plenty of additional storage. Roof, tuckpointing, plumbing, electrical, and HVAC systems have been updated. The dual zone furnace/AC will provide comfort and contribute to energy savings. The new energy-efficient double-paned windows throughout the property will provide optimal insulation and noise reduction. This home sits on a quiet block near expressways, transportation, and new developments coming to the neighborhood. Plus, you'll love the convenience of being just a short distance from the grocery store and other neighborhood amenities. Don't miss out on this amazing opportunity to own a beautiful home in Chicago's growing east Chatham neighborhood. Welcome home!
    House 2: 749000, 4 bedrooms, 4 bathrooms, Gold Coast, CONDO, 1320 N State Pkwy #12-13C, Stepping into this duplex home, feels like a single-family residence at nearly 4300 square feet. One is greeted by a soaring two-story paneled living room, an adjacent library with  a gracious formal dining room that is flooded with western sun and perfect for entertaining. The "chefs" kitchen with an informal eating area, can work for day-to-day meals but also is large enough to accommodate food preparation for larger gatherings.  There are four spacious en-suite bedrooms each with an abundance of closet space; 3 of which are on the upper level, complimented by a cozy reading loft that overlooks the living room. Stunning hardwood floors and crown moldings throughout the home are in stunning condition.   This incredible luxury 1920's high-rise community, designed by the renowned architect Robert De Goyler, nestled in Chicago's illustrious Gold Coast district is a cooperative apartment offering timeless elegance, incredible 24-hour service from door-staff, full engineering team and on-site management. The building is complimented by a stunning lobby, service elevators, gym, party room and outdoor terrace with grills.  The grandeur of this vintage coop is evident in every corner, from the high ceilings adorned with ornate moldings to the gleaming hardwood floors. With its prime location in the prestigious Gold Coast, this home offers unparalleled access to Chicago's finest dining, shopping, and cultural attractions as well as several options for elementary, middle and high schools.   Experience the epitome of luxury living at 1320 North State Parkway, where every detail has been thoughtfully curated to evoke a sense of timeless elegance and refinement. Don't miss your chance to own a piece of Chicago history.  HOA FEE-3186.30, RESERVE ASSESSMENT=1808.89, TAXES PAID MONTHLY=1759.73
    House 3: 575000, 5 bedrooms, 3 bathrooms, East Garfield Park, SINGLE_FAMILY, 3216 W Walnut St, Welcome to your new home in sought after East Garfield Park!  Beautifully rehabbed 5 bedrooms 3 bathrooms single family home located on a serene treelined street!  As you step through the front door you are greeted by the charming family room that boosts large south facing windows, high ceilings and a cozy gas fireplace.  Separate dining room and a completely rehabbed eat in kitchen. Large bedroom on the first floor for guests or perfect for work from home. Massive basement perfect for entertaining or second living space!  Second floor has four bedrooms, two bathrooms, and a separate laundry room!  This forever home is on an extra wide lot with a 2 car garage and is perfect for fur babies to run around, bbqs and summer gatherings!  Let's not forget the amazing location, 1.5 block from the Kedzie green line stop, close to 290, a short ride downtown, and the beautiful Garfield Park Conservatory. Nothing else to do but move in and enjoy a life a luxury!    CITI Bank special financing $7,500 closing credit, 3% down, and NO PMI!!
    House 4: 450000, 3 bedrooms, 2 bathrooms, Oriole Park, SINGLE_FAMILY, 5427 N Oconto Ave, Get ready to cozy up to a fire in your amazing extra large yard. Entertain in your beautiful sun drenched addition! Have breakfast in your updated eat in kitchen! This home has it all! Beautiful hardwood floors, updates include a new roof, copper plumbing, tankless water heater, fresh tuckpointing, new windows, new siding, 200amp electrical service, New/ Central air/heat with new ductwork all within the past 4 yrs! Long driveway leads to a 1 car garage with additional storage space! The house is completely hardwired every room with data cable, phone lines, and coax cable. (media center in laundry room with five rooms hardwired under Cable, 2 Data lines, phone.) The home is situated on a very quiet street around the corner from Oriole Park School! Harlem Foster Shopping Centre - Jewel-Osco, Walgreens, Planet Fitness, Cozy Corner, Starbucks, Dunkin Donuts. It is a commuter's dream near the 90/94 expressway, the Blue Line Harlem station & O'Hare Airport. Don't miss this amazing opportunity!
    House 5: 135000, 1 bedroom, 1 bathroom, Rogers Park, CONDO, 2056 W Jarvis Ave #1, Move in ready! Recently rehabbed one bedroom apartment. Updated furnace, fridge, bathroom updates, light fixtures, paint, and more. Stainless steel appliances in a good sized kitchen. Includes central ac along with laundry in unit! Conveniently one floor above level, including a deck off the back door. Perfect first time home buyer opportunity!
    House 6: 235000, 2 bedrooms, 2 bathrooms, Woodlawn, CONDO, 6500 S Minerva Ave #2-N, Beautifully maintained 2 Bedroom 2 Bathroom unit in the highly desirable Woodlawn neighborhood. Hard wood floors through out, newer stainless steel appliances, 1 year old furnace, 2 year old hot water heater, in-unit laundry, 1 assigned gated parking space. Conveniently located near the train station, The Museum of Science & Industry, Lake Michigan, Jackson Park & Washington Park. Make you appointment soon this wont last long on the market.
    House 7: 580000, 3 bedrooms, 3 bathrooms, West Town, CONDO, 2156 W Ohio St #1W, Located on a charming residential street within the bustling heart of West Town, this expansive 3bed/ 3bath duplex down offers a true sense of home. As you enter, you will immediately notice the abundant natural sunlight streaming through the stunning oversized south-facing windows. The spacious layout offers plenty of space for living room/dining room setup along with an open kitchen, perfect for entertaining.  Cozy gas fireplace, ideal for both relaxation and gatherings.  The kitchen features granite countertops, modern cabinetry and stainless-steel appliances.  This home has been meticulously maintained with hardwood flooring in the upper level, brand new high quality carpeting in the lower level, new lighting and paint throughout.  The main level features the primary bedroom with an en-suite bathroom/jacuzzi bath and private deck along with the second bedroom and additional full bathroom.  Lower level features an additional oversized living area 3rd bedroom, full bathroom, outdoor patio, gas fireplace and side by side laundry with new washer. Tandem parking and additional storage also included.  Low assessments, investor friendly.  Prime West Town location with close proximity to the West Loop, Ukrainian Village, nightlife and highway accessibility.  Embrace the epitome of city living while enjoying the peacefulness of being situated on a pretty residential street.
    House 8: 485000, 2 bedrooms, 2 bathrooms, Goose Island, CONDO, 845 N Kingsbury St UNIT 510, Spectacular Modern bright and spacious 2bed+den/2bath condo with premium garage parking and brand new hardwood floors in prime River North location! Perfect corner unit with north & west views, open floorplan, floor to ceiling windows. Unit offers BRAND NEW hardwood floors, stainless steel appliances, granite counters and an enormous island for additional seating. The primary bedroom has custom built-in walk-in closet, an en-suite bath with stone counters and large shower. In-unit full-size washer and dryer and deeded parking in a heated garage. River North views from balcony large enough for grill and outdoor sofa. Location cannot be better for shopping, dining, and enjoying life-- walkable access to public transportation (including bus stop and L), restaurants, dog parks, Target, Amazon Go, downtown and plenty more. Convenient access to I-90/94. Heated garage spot is deeded and INCLUDED in price. Prime corner parking spot!
    House 9: 335000, 2 bedrooms, 2 bathrooms, North Kenwood, CONDO, 4351 S Lake Park Ave APT 2N, Just gorgeous! Fully upgraded 2b/2b on beautiful Lake Park Ave. This beautiful unit is fully upgraded with hardwood floors through-out, custom lighting and window treatments, wainscotting on the walls, and many other luxury appointments. The great room is centered with cozy fireplace with custom built-ins and there is plenty of room for large living/dining room furniture. The kitchen is stunning! Custom white cabinetry to the ceiling, a range hood, a built microwave, a pantry, beautiful granite countertops, a breakfast bar and top-tier appliances. Few condos have a high-end kitchen like this one. The primary bedroom has a walk-in closet with custom shelving, and a huge private bathroom with heated floors, a luxurious bath tub, a walk-in shower with body sprays, two separate vanities and marble floors/walls. It's like being at a spa! The second bedroom has been customized with a built-in murphy bed in the wall perfect for guest; but smartly designed so the room can also be used as an office/den/exercise room. All of this plus an in-unit washer/dryer, balcony, a huge storage locker, and covered parking. It is a beautiful and well managed building with a roof deck for residents to enjoy lake and skyline views. Walk to the lake, and enjoy a short drive to Hyde Park, South Loop, and all that Kenwood/Bronzeville has to offer. Won't last long!

    The houses that the customer like the most are House ('a > b' means the customer likes House 'a' more than House 'b'):
    """
    # The houses that the customer like the most are House (ordered by preference from most liked to least liked):
    #     The houses that you like the most are House {' '.join(map(str, input_ranking))}.
    #     Factors influenced your likes, by highlighting and explaining your choice like the example below:
    #     {
    # ''.join([factor_to_string(k, v0, v1) for k, (v0, v1) in factors.items()])
    # }

    # Please rank the following houses in order of preference from most liked to least liked.
    template2 = f"""
    
    [Second Batch: Sample Data from the customer]
    
    House 0: 334000, 6 bedrooms, 3 bathrooms, East Garfield Park, MULTI_FAMILY, 622 N Spaulding Ave, This graystone 2 flat ,  living room has plenty of windows for natural light.  separate force air heat, full unfinished basement  that could be duplex  up to 1st floor
    House 1: 65000, 2 bedrooms, 1 bathroom, South Shore, CONDO, 2569 E 71st St #1N, Sprawling & spacious condo in desirable Shore Club Condominiums! Offering picturesque views of Lake Michigan & The South Shore Golf Course from every window, this home boasts a large living room with fireplace & built-in bookshelves; Formal dining room to enjoy family dinners; 2 spacious bedrooms; Amazing sunroom/office with a wall of windows offering breathtaking views & kitchen with door to the outdoor balcony! Building has security gates, cameras & an intercom system. Great location near public transportation, shopping, dining, park, golf course & lake.
    House 2: 450000, 2 bedrooms, 2 bathrooms, Printers Row, CONDO, 547 S Clark St APT 1101, Welcome to urban living at its finest on Printer's Row! This newly renovated 2-bedroom, 2-bath gem is perched on the 11th floor, providing breathtaking views that stretch above the neighboring buildings! With PARKING INCLUDED, private and secure entry, and a convenient elevator, your new home seamlessly blends comfort and style. As you step inside the condo, be greeted by an abundance of natural light flooding through the many windows, highlighting the high ceilings and maple hardwood floors that grace this immediate space. Cozy up by the gas fireplace in the open-concept living area, perfect for entertaining!   The kitchen boasts, a gorgeous new eat in counter, all-new stainless steel appliances, matching countertops, new subway tile splash, and an inviting eat-in bar. Upgraded countertops, 42-inch cabinets, and a stove with a center griddle complete the kitchen, making it a chef's dream.   Closet organizers in each bedroom ensure optimal storage, while the main bedroom offers a walk-in closet, a bathroom featuring a whirlpool tub, a double sink, and a shower cabinet. Berber carpeting adds a touch of luxury and warmth to the bedrooms. Convenience continues with an in-unit laundry featuring an oversized washing machine.  Deeded parking is just the beginning, with additional rental options nearby, though with all the city has to offer just outside your door, who needs a car? Explore the vibrant neighborhood that surrounds you, with restaurants, shopping, Grant Park, Millennium Park, State Street, the Harold Washington Library, museums, theaters, and the lakefront all within reach. The HOA takes care of essentials like cable, internet, gym access, garbage, water, bike storage, and a locker.
    House 3: 850000, 4 bedrooms, 4 bathrooms, Pulaski Park, SINGLE_FAMILY, 6033 N Jersey Ave, The house is all paint in neutral color - the photos were taken before the paint. Chicago's best kept secret! This beautifully appointed style home has a 4 bedrooms 3.5 bath open floor plan on oversized lot. The formal living room with custom built-ins, crown moldings, gas fireplace and pretty bay window flows into the separate dining room. Thoughtfully designed chef's kitchen with 42" cabinets, granite countertops, s/s appliances and glass backsplash. There is a perfect family room off the kitchen. A bedroom & full bath complete the first floor. Second floor is the complete master bedroom and bathroom with a shower and Jacuzzi and double vanity. The fully finished walkout lower level offers a second rec/fam room, full bath, third and fourth bedroom, den, laundry, & storage. Refinished hardwood floors throughout custom window treatments, 3 fireplaces, beautiful landscaped yard, patio, new concrete pathway & 2 car garage, deck over the garage. Lovely backyard.
    House 4: 399900, 2 bedrooms, 2 bathrooms, Gold Coast, CONDO, 1000 N Lake Shore Dr APT 1508, WOW !!! Welcome to the epitome of luxury living with a million-dollar view! This exquisite residence offers a panoramic perspective, providing a full lake view that stretches from the south to the north. Imagine waking up to breathtaking sunrises and winding down your day with the tranquil beauty of evening sunsets-truly a Gold Coast living experience.    Step into this beautiful and spacious high-floor 2-bedroom, 2-bathroom unit, adorned with hardwood flooring throughout. As you enter through the front foyer, you are greeted by a well-appointed kitchen featuring ample cabinets and stainless steel appliances. The seamless flow from the kitchen leads you to the dining space, unveiling a breathtaking panoramic view of the lake that extends through the entire living room. This is a quiet building with separate, secured sides to the building and each floor, professionally managed, 24/7 front door staff, a roof deck, storage, laundry room and on-site engineers. Heated, valet garage parking is available for rent, with weekly car wash included.     Both bedrooms in this unit are generously sized, offering plenty of closet space. The primary bedroom is a sanctuary of convenience with an en-suite bathroom. Enjoy the convenience of walking to Oak Street Beach and the scenic lake paths for running or biking. Explore the upscale shopping on Michigan Avenue and Oak Street, indulge in fine dining experiences, practice yoga at nearby studios, maintain a healthy lifestyle with proximity to health clubs, and revel in the vibrant nightlife of Rush Street.
    House 5: 215000, 2 bedrooms, 1 bathroom, Hollywood Park, CONDO, 3257 W Olive Ave APT 1E, Beautiful 2 bedroom / 1 bathroom condo features large bright living room, updated open kitchen concept with stainless steel appliances, large bedrooms! Hardwood floors through-out. 2 in 1 washer/dryer in unit (kitchen). Bathroom was updated within the last year. Pet friendly building. Renters welcome. Coin laundry and storage room in the basement. Close to Northeastern Illinois University, shopping, and dining. Don't miss out on this great opportunity!
    House 6: 575000, 4 bedrooms, 4 bathrooms, West Humboldt Park, SINGLE_FAMILY, 1137 N Karlov Ave, THE PURCHASE MIGHT QUALIFY FOR A GRANT OF $20,000.   This NEW CONSTRUCTION Single Family home has just been completed and is built on an oversized lot. It features 4 bedrooms, 3.5 bathrooms, separate living and dining rooms, spacious family room in the basement. The chef's kitchen features white custom made cabinets with soft close doors and drawers, SS appliances, quartz counter, a farmhouse style sink and a large peninsula. The finished basement offers an additional bedroom with a walk-in closet, wet bar with a wine cooler, utility room, high efficient furnace, water heater, sump pump, ejector pump. There are maple floors on the main floor and on the second floor. A large patio, back porch, front steel steps, and a detached 2-car garage with a party door are other features of this gorgeous house!
    House 7: 239900, 4 bedrooms, 3 bathrooms, South Shore, SINGLE_FAMILY, 7011 S Cornell Ave, Unique, compelling opportunity. In the heart of South Shore. Walking distance to the highly anticipated Obama library, 63rd street beach, Jackson Park golf course, "New construction". The house is 90% complete, all HVAC, plumbing, electrical, has been roughed and completed. All you have to do is drywall and the cosmetics. Concrete new, foundation new, porches new, garage new, furnaces  new, A/C's new. What more can you ask for! Avoid the high prices of material.  Wonderful for a quick flip or build generational wealth, long term as a luxury homeowner, or let this be a cash cow as a rental or Airbnb. Area is gentrifying at a rapid pace. Approved Architect plans included. Future upside/ possibilities are endless. Sold "as is"  Request your showing today.
    House 8: 415000, 9 bedrooms, 6 bathrooms, Grand Crossing, MULTI_FAMILY, 7049 S Dante Ave, Fully Occupied Property. Fully occupied 3-unit building. Each unit features 3bed/2baths, In Unit Washer/Dryer, Kitchen Appliances.  Central A/C and Heat. Great for investors and first-time home buyers. Steps away from the Metra, Stony Island, and Lake Shore Drive. Located in BOOMING South Shore area, so take advantage and invest in this market right now. There are MAJOR area developments ahead and it is on the rise!
    House 9: 317901, 4 bedrooms, 2 bathrooms, West Englewood, SINGLE_FAMILY, 7229 S Wood St, BRING THOSE BUYERS OUT THEY WILL NOT BE DISSAPOINTED WITH THIS BEAUTIFUL COMPLETE REHAB BYLEVEL HOME. THE 1ST FLOOR OFFERS AN OPEN FLOOR PLAN NEW HARDWOOD FLOORS, NEW PORCELAIN TILE FLORING A CENTER ISALND WITH A BUILD IN MICROWAVE. ALL NEW STAINLESS STEEL GE APPLIANCES QUARTZ COUNTER TOPS CUSTOM SHAKER CABINETS WITH A BEAUTIFULL BLACK TILE SPLASH WALL. THERE IS AN ELECTRICAL FIRE PLACE IN THE LIVING ROOM. THE SECOND FLOOR HAS A TOTAL OF 3 VERY GENEROUS-SIZE BEDROOMS WITH GOOD-SIZE CLOSETS. THE MASTER BEDROOM HAS HIS & HER CLOSETS. A NEW CUSTOM BATHROOM WITH A SHAKER VANITY CABINET WITH A QUARTZ COUNTER TOP. THE LOWER LEVEL HAS A NICE-SIZE FAMILY ROOM AND A 4TH BEDROOM WITH A GOOD-SIZE CLOSET. IT ALSO HAS A NEW CUSTOM, FULL BATH WITH SHAKER VANITY AND QUARTZ COUNTOP AS WELL. THE LAUNDRY ROOM HAS A NEW GE WASHER AND DRYER AND NEW VINYL WOOD FLOORING. THERE IS WAYNES COATING, CROWN MOLDING THROUGH OUT THE ENTIRE HOUSE.    THE PROPERTY WAS NICELY PAINTED THROUGH OUT AS WELL THERE IS JUST TOO MUCH TO LIST, YOUR BUYERS WOULD LOVE TO CALL THIS PLACE HOME...!!!!!

    The houses that the customer like the most are House ('a > b' means the customer likes House 'a' more than House 'b'):
    """

    # The houses that you like the most are House (ordered by preference from most liked to least liked):
    chenghao_preference = [[0, 3], [2, 4, 6]]
    jibang_preference = [[5, 6], [5, 1]]
    chaoqi_preference = [[0, 7, 9], [2, 3, 4]]
    simon_preference = [[2, 4, 5], [4, 6, 2]]

    names = ['chenghao', 'jibang', 'chaoqi', 'simon']
    responses = []
    # dump_filename = "preference_analysis_responses.pkl"
    dump_filename = "preference_analysis_responses_binary_feedback.pkl"
    def generate_pairwise_preference(preference):
        buf = []
        for i in range(len(preference)):
            for j in range(i + 1, len(preference)):
                buf.append("{} > {}".format(preference[i], preference[j]))
        non_selected_houses = set(range(10)) - set(preference)
        for prefered_id in preference:
            for non_selected_id in non_selected_houses:
                buf.append("{} > {}".format(prefered_id, non_selected_id))
        return buf

    if not os.path.exists(dump_filename):
        for name, preference in zip(names, [chenghao_preference, jibang_preference, chaoqi_preference, simon_preference]):
            # prompt = template + ", ".join([str(x) for x in preference[0]]) + template2 + ", ".join([str(x) for x in preference[1]]) + "\n-----------\n"
            prompt = template + ", ".join([str(x) for x in generate_pairwise_preference(preference[0])]) + template2 + ", ".join([str(x) for x in generate_pairwise_preference(preference[1])]) + "\n-----------\n"
            prompt = prompt + "Analysis from the five dimensions (Price, Location, Home features/Amenity, House Size, Investment Value), in the format of '[dimension]:[analysis]' in seperate lines. : \n"
            response = chat_manager.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a helpful assistant for analyzing house buyer preference. Ideally after detailed aspect-level analysis, give me a summary."},
                    {"role": "user", "content": prompt}
                ]
            )
            responses.append({"name": name, "preference": preference, "response": response, "prompt": prompt})
            print("Analyzing {}'s preference: \n".format(name), response.choices[0].message.content)
        pickle.dump(responses, open(dump_filename, "wb"))
        print("Responses saved to {}".format(dump_filename))
    else:
        responses = pickle.load(open(dump_filename, "rb"))
    # write out to csv files
    import csv
    header = list(responses[0].keys())
    with open(dump_filename.replace(".pkl", ".csv"), "w", newline='') as f:
        writer = csv.DictWriter(f, fieldnames=header)
        writer.writeheader()
        for response in responses:
            response_text = response['response'].choices[0].message.content
            writer.writerow({
                "name": response['name'],
                "preference": response['preference'],
                "response": response_text,
                "prompt": response['prompt']
            })



